workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx1024m"
        ANDROID_HOME: /usr/local/share/android-sdk
    scripts:
      - name: Manual Install Latest Command-Line Tools (v13.0)  # Clean install
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # Key: Zulu 8 for sdkmanager
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-13114758_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "Latest cmdline-tools installed. PATH: $PATH"
      - name: Install Android SDK 35 & Build Tools + Platform Tools  # Updated for SDK 35
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # Key: For proper installation
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          sdkmanager --uninstall "build-tools;33.0.1" "build-tools;34.0.0" "build-tools;35.0.0" "platform-tools" || true
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          yes | sdkmanager --licenses
          $ANDROID_HOME/build-tools/35.0.0/aapt2 version  # Verify
          echo "SDK 35 installed with proper tools!"
      - name: Install/Update Gradle via Homebrew  # New: Ensure Gradle available for wrapper generation
        script: |
          brew install gradle
          export PATH=/opt/homebrew/bin:$PATH  # For M2 macOS
          gradle --version
          echo "Gradle installed/updated successfully"
      - name: Generate Gradle wrapper  # Updated: Specify version for AGP 8.5 compatibility
        script: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:/opt/homebrew/bin:$PATH
          cd $CM_BUILD_DIR  # Ensure in project root
          if [ ! -f "gradlew" ]; then
            gradle wrapper --gradle-version 8.10  # Stable for AGP 8.5.2 & SDK 35
            chmod +x gradlew
          else
            echo "Gradle wrapper already present"
          fi
          ./gradlew --version  # Verify
          echo "Gradle wrapper generated!"
      - name: Set Android SDK location in local.properties  # New: Codemagic standard for Gradle to find SDK
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "Local properties set with SDK path"
      - name: Build debug APK
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # For Gradle if needed
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:/opt/homebrew/bin:$PATH
          cd $CM_BUILD_DIR
          ./gradlew clean assembleDebug  # Clean build
    artifacts:
      - app/build/outputs/apk/debug/*.apk  # Updated: Specific to debug APK
