workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx1024m"
    scripts:
      - name: Generate Gradle wrapper
        script: |
          gradle wrapper
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
