workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx1024m"
        ANDROID_HOME: /usr/local/share/android-sdk  # Explicit for safety
    scripts:
      - name: Manual Install Latest Command-Line Tools (v13.0)  # Manual download to fix XML v4 & AAPT
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          # Download latest macOS command-line tools (v13.0, fixes XML v4 support)
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-13114758_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest
          # Update PATH
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          # Accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "Latest cmdline-tools (v13.0) installed & PATH updated: $PATH"
      - name: Install Android SDK 34 & Build Tools  # Now with new tools
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          # Uninstall old to avoid corruption
          sdkmanager --uninstall "build-tools;33.0.1" "build-tools;34.0.0" || true
          # Install fresh
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses
          # Verify AAPT from new build-tools (should print version without error)
          $ANDROID_HOME/build-tools/34.0.0/aapt2 version
          echo "SDK 34 & Build-Tools 34.0.0 installed! AAPT ready for API 34 attributes."
      - name: Generate Gradle wrapper
        script: |
          ./gradlew wrapper
      - name: Build debug APK
        script: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
