workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx2048m"
        ANDROID_HOME: /usr/local/share/android-sdk
    scripts:
      - name: Manual Install Latest Command-Line Tools (v13.0)
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-13114758_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "Latest cmdline-tools installed. PATH: $PATH"
      - name: Install Android SDK 35 & Build Tools + Platform Tools
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          sdkmanager --uninstall "build-tools;33.0.1" "build-tools;34.0.0" "build-tools;35.0.0" "platform-tools" || true
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          yes | sdkmanager --licenses
          $ANDROID_HOME/build-tools/35.0.0/aapt2 version
          echo "SDK 35 installed with proper tools!"
      - name: Install/Update Gradle via Homebrew
        script: |
          export HOMEBREW_PREFIX="/opt/homebrew"
          export PATH="$HOMEBREW_PREFIX/bin:$PATH"
          brew update
          brew install gradle || brew upgrade gradle
          gradle --version || echo "Gradle install failed - checking path"
          which gradle || echo "Gradle not in PATH: $PATH"
          echo "Gradle installed/updated successfully. Version: $(gradle --version | head -n1)"
      - name: Generate Gradle wrapper
        script: |
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$HOMEBREW_PREFIX/bin:$PATH"
          cd $CM_BUILD_DIR
          pwd
          ls -la
          if [ ! -f "gradlew" ]; then
            echo "Generating wrapper in root..."
            gradle wrapper --gradle-version 8.8 || {
              echo "Root generation failed, trying in app module..."
              cd app
              gradle wrapper --gradle-version 8.8
              cd ..
            }
            if [ ! -f "gradlew" ]; then
              echo "Manual download fallback..."
              mkdir -p gradle/wrapper
              wget -q https://services.gradle.org/distributions/gradle-8.8-bin.zip
              unzip -q gradle-8.8-bin.zip
              cp gradle-8.8/gradle/wrapper/gradle-wrapper.jar gradle/wrapper/ || true
              cp gradle-8.8/gradlew .
              cp gradle-8.8/gradlew.bat .
              chmod +x gradlew gradlew.bat
              if [ ! -f "gradle/wrapper/gradle-wrapper.properties" ]; then
                echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
                echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
                echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
                echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.8-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
              fi
              rm -rf gradle-8.8 gradle-8.8-bin.zip
              echo "Manual wrapper setup complete"
            fi
            chmod +x gradlew
            echo "Wrapper files: $(ls -la gradlew gradle/wrapper/ 2>/dev/null || echo 'Missing')"
          else
            echo "Gradle wrapper already present"
          fi
          if [ -f "./gradlew" ]; then
            ./gradlew --version || echo "Wrapper version check failed"
            echo "Gradle wrapper generated successfully!"
          else
            echo "ERROR: gradlew still not created - build will fail"
            exit 1
          fi
      - name: Set Android SDK location in local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "sdk.dir=$ANDROID_HOME" > app/local.properties 2>/dev/null || true
          cat local.properties
          echo "Local properties set with SDK path"
      - name: Build debug APK
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$HOMEBREW_PREFIX/bin:$PATH"
          cd $CM_BUILD_DIR
          if [ ! -f "./gradlew" ]; then
            echo "ERROR: gradlew missing - cannot build"
            ls -la
            exit 1
          fi
          echo "Running build with Gradle $(./gradlew --version | head -n1)"
          ./gradlew clean assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - build/outputs/apk/debug/*.apk
