workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx1024m"
        ANDROID_HOME: /usr/local/share/android-sdk
    scripts:
      - name: Manual Install Latest Command-Line Tools (v13.0)  # Clean install
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # Key: Zulu 8 for sdkmanager
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-13114758_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "Latest cmdline-tools installed. PATH: $PATH"
      - name: Install Android SDK 34 & Build Tools + Platform Tools  # With Java 8
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # Key: For proper installation
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          sdkmanager --uninstall "build-tools;33.0.1" "build-tools;34.0.0" "platform-tools" || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses
          $ANDROID_HOME/build-tools/34.0.0/aapt2 version  # Verify
          echo "SDK 34 installed with proper tools!"
      - name: Generate Gradle wrapper
        script: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          gradle wrapper
          echo "Gradle wrapper generated!"
      - name: Build debug APK
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home  # For Gradle if needed
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          ./gradlew clean assembleDebug  # Clean build
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
