workflows:
  android-build:
    name: Android build
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx1024m"
    scripts:
      - name: Install Latest Command-Line Tools & Accept Licenses  # Key fix: Update cmdline-tools for XML v4 support
        script: |
          # Accept licenses first
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          # Install latest cmdline-tools (for AAPT XML v4 & API 34 support)
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmdline-tools;latest"
          # Update PATH to use new cmdline-tools
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          # Re-accept licenses with updated tools
          yes | sdkmanager --licenses
          echo "Latest cmdline-tools installed!"
      - name: Install Android SDK 34 & Build Tools  # Now with updated tools
        script: |
          # Install platform and build tools for API 34
          sdkmanager "platforms;android-34" "build-tools;34.0.0"
          # Final license accept
          yes | sdkmanager --licenses
          echo "SDK 34 installed successfully!"
      - name: Generate Gradle wrapper
        script: |
          gradle wrapper
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
